import { ComponentType } from '../../../types';
import { ComponentPropertySchema, PropertyMetadata, PropertyGroup, PropertyContext } from '../metadata';
import { commonProperties, commonTabs, commonGroups, createPropertySchema } from '../registry';

/**
 * Button-specific property definitions
 */
const buttonProperties: PropertyMetadata[] = [
  {
    id: 'text',
    label: 'Text',
    type: 'expression',
    defaultValue: 'Click Me',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.BUTTON],
    tooltip: 'Button text content',
    placeholder: 'e.g. Submit',
  },
  {
    id: 'variant',
    label: 'Variant',
    type: 'dropdown',
    defaultValue: 'solid',
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.BUTTON],
    tooltip: 'Button style variant',
    options: [
      { value: 'solid', label: 'Solid' },
      { value: 'outlined', label: 'Outlined' },
      { value: 'ghost', label: 'Ghost' },
      { value: 'text', label: 'Text' },
    ],
  },
  {
    id: 'size',
    label: 'Size',
    type: 'dropdown',
    defaultValue: 'md',
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.BUTTON],
    tooltip: 'Button size variant',
    options: [
      { value: 'sm', label: 'Small' },
      { value: 'md', label: 'Medium' },
      { value: 'lg', label: 'Large' },
    ],
  },
  {
    id: 'fullWidth',
    label: 'Full Width',
    type: 'boolean',
    defaultValue: false,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 3,
    applicableTo: [ComponentType.BUTTON],
    tooltip: 'Whether button stretches to full container width',
  },
  {
    id: 'loading',
    label: 'Loading',
    type: 'expression',
    defaultValue: false,
    supportsExpression: true,
    group: 'State',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 1,
    propertyOrder: 2,
    applicableTo: [ComponentType.BUTTON],
    tooltip: 'Show loading spinner and disable interaction',
    placeholder: 'e.g. {{isSubmitting}}',
  },
  {
    id: 'iconLeft',
    label: 'Icon Left',
    type: 'string',
    defaultValue: '',
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 4,
    applicableTo: [ComponentType.BUTTON],
    tooltip: 'Icon or text to show before button text',
    placeholder: 'e.g. + or icon text',
  },
  {
    id: 'iconRight',
    label: 'Icon Right',
    type: 'string',
    defaultValue: '',
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 5,
    applicableTo: [ComponentType.BUTTON],
    tooltip: 'Icon or text to show after button text',
    placeholder: 'e.g. arrow symbol',
  },
  {
    id: 'backgroundColor',
    label: 'Background Color',
    type: 'color',
    defaultValue: '#4f46e5',
    supportsExpression: true,
    group: 'Styling',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.BUTTON],
    tooltip: 'Button background color',
  },
  {
    id: 'textColor',
    label: 'Text Color',
    type: 'color',
    defaultValue: '#FFFFFF',
    supportsExpression: true,
    group: 'Styling',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.BUTTON],
    tooltip: 'Button text color',
  },
  {
    id: 'actionType',
    label: 'Action Type',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.BUTTON],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Show Alert' },
      { value: 'updateVariable', label: 'Update Variable' },
      { value: 'executeCode', label: 'Execute Code' },
      { value: 'submitForm', label: 'Submit Form' },
      { value: 'navigate', label: 'Navigate to Page' },
    ],
    tooltip: 'Action to perform when button is clicked',
  },
  {
    id: 'actionAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'alert',
    tooltip: 'Message to display in alert',
    placeholder: 'e.g. Hello World!',
  },
  {
    id: 'actionVariableName',
    label: 'Variable Name',
    type: 'string',
    defaultValue: '',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 4,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'updateVariable',
    tooltip: 'Name of variable to update',
    placeholder: 'e.g. counter',
  },
  {
    id: 'actionVariableValue',
    label: 'Variable Value',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 5,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'updateVariable',
    tooltip: 'Value to set for variable',
    placeholder: 'e.g. {{counter + 1}}',
  },
  {
    id: 'actionCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 3,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'executeCode',
    tooltip: 'JavaScript code to execute',
    placeholder: 'e.g. console.log("Hello")',
  },
  {
    id: 'actionOnSubmitCode',
    label: 'On Submit Success Code',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 6,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'submitForm',
    tooltip: 'Code to execute after successful form validation. Use {{formData}} to access collected form values.',
    placeholder: 'e.g. {{ console.log(formData) }}',
  },
  {
    id: 'actionPageId',
    label: 'Target Page',
    type: 'dropdown',
    defaultValue: '',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 7,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'navigate',
    tooltip: 'Select the page to navigate to',
    options: (context: PropertyContext) => {
      const pages = context.evaluationScope?.pages;
      if (!Array.isArray(pages)) return [];
      return pages.map((p: { id: string; name: string }) => ({ value: p.id, label: p.name }));
    },
  },
  {
    id: 'actionPageExpression',
    label: 'Page Expression',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 8,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'navigate',
    tooltip: 'Dynamic expression that evaluates to a page ID (overrides static Target Page when set)',
    placeholder: 'e.g. {{targetPageId}}',
  },
  {
    id: 'validateBeforeNavigate',
    label: 'Validate Before Navigate',
    type: 'boolean',
    defaultValue: false,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 9,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'navigate',
    tooltip: 'Validate all form fields on the current page before navigating (blocks navigation on failure)',
  },
];

/**
 * Button-specific groups
 * Order values use DEFAULT_GROUP_ORDER from registry for consistency
 */
const buttonGroups: PropertyGroup[] = [
  { id: 'Events', label: 'Events', tab: 'Events', collapsible: true, defaultCollapsed: false },
];

/**
 * Button property schema
 */
export const buttonSchema: ComponentPropertySchema = createPropertySchema(
  ComponentType.BUTTON,
  buttonProperties,
  commonTabs,
  [...commonGroups, ...buttonGroups]
);

