import { ComponentType } from '../../../types';
import { ComponentPropertySchema, PropertyMetadata, PropertyGroup, PropertyTab } from '../metadata';
import { commonProperties, commonTabs, commonGroups, createPropertySchema, DEFAULT_GROUP_ORDER, formValidationProperties, formAccessibilityProperties, formStateProperties, formGroups } from '../registry';
import { SharedEventsGroupRenderer } from './shared-events-renderer';

/**
 * Checkbox-specific property definitions
 */
const checkboxProperties: PropertyMetadata[] = [
  {
    id: 'label',
    label: 'Label',
    type: 'expression',
    defaultValue: 'Accept terms',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.CHECKBOX],
    tooltip: 'Checkbox label text',
    placeholder: 'e.g. I agree to the terms',
  },
  {
    id: 'defaultValue',
    label: 'Default Value',
    type: 'expression',
    defaultValue: false,
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.CHECKBOX],
    tooltip: 'Initial checked state',
  },
  {
    id: 'description',
    label: 'Description',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.CHECKBOX],
    tooltip: 'Secondary description text below the label',
    placeholder: 'e.g. Additional info',
  },
  {
    id: 'hideDescriptionWhenChecked',
    label: 'Hide Description When Checked',
    type: 'boolean',
    defaultValue: false,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 3,
    applicableTo: [ComponentType.CHECKBOX],
    tooltip: 'Hide the description text after the checkbox is checked',
    visibleIf: (props) => !!(props as any).description,
  },
  {
    id: 'accentColor',
    label: 'Accent Color',
    type: 'color',
    defaultValue: '',
    supportsExpression: true,
    group: 'Styling',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.CHECKBOX],
    tooltip: 'Accent color for the checkbox',
  },
  {
    id: 'indeterminate',
    label: 'Indeterminate',
    type: 'boolean',
    defaultValue: false,
    supportsExpression: true,
    group: 'Advanced',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: DEFAULT_GROUP_ORDER['Advanced'],
    propertyOrder: 0,
    applicableTo: [ComponentType.CHECKBOX],
    tooltip: 'Show indeterminate (mixed) state',
    placeholder: 'e.g. true or {{someCondition}}',
  },
  // Spread shared form properties
  ...formValidationProperties.map(p => ({ ...p, applicableTo: [ComponentType.CHECKBOX] as any })),
  ...formAccessibilityProperties.map(p => ({ ...p, applicableTo: [ComponentType.CHECKBOX] as any })),
  ...formStateProperties.map(p => ({ ...p, applicableTo: [ComponentType.CHECKBOX] as any })),
  // Layout properties - zIndex
  {
    id: 'zIndex',
    label: 'Z-Index',
    type: 'expression',
    defaultValue: undefined,
    supportsExpression: true,
    group: 'Layout',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 1,
    propertyOrder: 4,
    applicableTo: [ComponentType.CHECKBOX],
    tooltip: 'Z-index for layering components (supports expressions)',
    placeholder: 'e.g. 1, 10, 100 or {{zIndex}}',
  },
  // Events Tab
  {
    id: 'onChangeActionType',
    label: 'On Change Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.CHECKBOX],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when checkbox value changes',
  },
  {
    id: 'onChangeAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.CHECKBOX],
    visibleIf: (props) => (props as any).onChangeActionType === 'alert',
    tooltip: 'Message to display in alert (supports expressions)',
    placeholder: 'e.g., {{ "Value changed: " + event.target.checked }}',
  },
  {
    id: 'onChangeCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.CHECKBOX],
    visibleIf: (props) => (props as any).onChangeActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when checkbox value changes',
    placeholder: 'e.g., {{ (() => { console.log(event.target.checked); })() }}',
  },
  // On Focus Action
  {
    id: 'onFocusActionType',
    label: 'On Focus Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 10,
    applicableTo: [ComponentType.CHECKBOX],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when checkbox gains focus',
  },
  {
    id: 'onFocusAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 11,
    applicableTo: [ComponentType.CHECKBOX],
    visibleIf: (props) => (props as any).onFocusActionType === 'alert',
    tooltip: 'Message to display in alert when checkbox gains focus (supports expressions)',
    placeholder: 'e.g., {{ "Checkbox focused" }}',
  },
  {
    id: 'onFocusCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 12,
    applicableTo: [ComponentType.CHECKBOX],
    visibleIf: (props) => (props as any).onFocusActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when checkbox gains focus',
    placeholder: 'e.g., {{ (() => { console.log("Focused"); })() }}',
  },
  // On Blur Action
  {
    id: 'onBlurActionType',
    label: 'On Blur Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 20,
    applicableTo: [ComponentType.CHECKBOX],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when checkbox loses focus',
  },
  {
    id: 'onBlurAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 21,
    applicableTo: [ComponentType.CHECKBOX],
    visibleIf: (props) => (props as any).onBlurActionType === 'alert',
    tooltip: 'Message to display in alert when checkbox loses focus (supports expressions)',
    placeholder: 'e.g., {{ "Checkbox blurred" }}',
  },
  {
    id: 'onBlurCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 22,
    applicableTo: [ComponentType.CHECKBOX],
    visibleIf: (props) => (props as any).onBlurActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when checkbox loses focus',
    placeholder: 'e.g., {{ (() => { console.log("Blurred"); })() }}',
  },
  // On Enter Key Press Action
  {
    id: 'onEnterActionType',
    label: 'On Enter Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 30,
    applicableTo: [ComponentType.CHECKBOX],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when Enter key is pressed',
  },
  {
    id: 'onEnterAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 31,
    applicableTo: [ComponentType.CHECKBOX],
    visibleIf: (props) => (props as any).onEnterActionType === 'alert',
    tooltip: 'Message to display in alert when Enter key is pressed (supports expressions)',
    placeholder: 'e.g., {{ "Enter key pressed" }}',
  },
  {
    id: 'onEnterCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 32,
    applicableTo: [ComponentType.CHECKBOX],
    visibleIf: (props) => (props as any).onEnterActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when Enter key is pressed',
    placeholder: 'e.g., {{ (() => { console.log("Enter pressed"); })() }}',
  },
];

/**
 * Checkbox-specific tabs - General, Styles, and Events
 */
const checkboxTabs: PropertyTab[] = [
  { id: 'General', label: 'General', order: 0 },
  { id: 'Styles', label: 'Styles', order: 1 },
  { id: 'Events', label: 'Events', order: 2 },
];

/**
 * Checkbox-specific groups
 * Note: Layout, State, and Styling are already in commonGroups, so we don't duplicate them
 * Order values use DEFAULT_GROUP_ORDER from registry for consistency
 */
const checkboxGroups: PropertyGroup[] = [
  { id: 'Basic', label: 'Basic', tab: 'General', collapsible: true, defaultCollapsed: false },
  { id: 'Validation', label: 'Validation', tab: 'General', collapsible: true, defaultCollapsed: false },
  { id: 'Appearance', label: 'Appearance', tab: 'General', collapsible: true, defaultCollapsed: false },
  { id: 'Accessibility', label: 'Accessibility', tab: 'General', collapsible: true, defaultCollapsed: true },
  { id: 'Advanced', label: 'Advanced', tab: 'Styles', collapsible: true, defaultCollapsed: true },
  {
    id: 'Events',
    label: 'Events',
    tab: 'Events',
    collapsible: true,
    defaultCollapsed: false,
    customGroupRenderer: SharedEventsGroupRenderer,
  },
];

/**
 * Checkbox property schema
 */
const checkboxSchemaBase = createPropertySchema(
  ComponentType.CHECKBOX,
  checkboxProperties,
  checkboxTabs,
  [...commonGroups, ...checkboxGroups]
);

// Filter out border properties (borderWidth, borderColor, borderRadius, borderStyle) and shadow property (boxShadow)
export const checkboxSchema: ComponentPropertySchema = {
  ...checkboxSchemaBase,
  properties: checkboxSchemaBase.properties.filter(
    prop => !['borderWidth', 'borderColor', 'borderRadius', 'borderStyle', 'boxShadow'].includes(prop.id)
  ),
};

