import { ComponentType } from '../../../types';
import { ComponentPropertySchema, PropertyMetadata, PropertyGroup } from '../metadata';
import { commonTabs, commonGroups, createPropertySchema, DEFAULT_GROUP_ORDER } from '../registry';

/**
 * Image-specific property definitions
 */
const imageProperties: PropertyMetadata[] = [
  // === Basic group ===
  {
    id: 'src',
    label: 'Image URL',
    type: 'expression',
    defaultValue: 'https://picsum.photos/200/200',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.IMAGE],
    tooltip: 'Image source URL or expression',
    placeholder: 'e.g. https://example.com/image.png or {{imageUrl}}',
  },
  {
    id: 'alt',
    label: 'Alt Text',
    type: 'expression',
    defaultValue: 'Placeholder Image',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.IMAGE],
    tooltip: 'Alternative text for accessibility',
    placeholder: 'e.g. Product image',
  },
  {
    id: 'objectFit',
    label: 'Object Fit',
    type: 'dropdown',
    defaultValue: 'cover',
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.IMAGE],
    options: [
      { value: 'cover', label: 'Cover' },
      { value: 'contain', label: 'Contain' },
      { value: 'fill', label: 'Fill' },
      { value: 'none', label: 'None' },
      { value: 'scale-down', label: 'Scale Down' },
    ],
    tooltip: 'How the image should fit within its container',
  },
  {
    id: 'objectPosition',
    label: 'Object Position',
    type: 'dropdown',
    defaultValue: 'center',
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 3,
    applicableTo: [ComponentType.IMAGE],
    options: [
      { value: 'center', label: 'Center' },
      { value: 'top', label: 'Top' },
      { value: 'bottom', label: 'Bottom' },
      { value: 'left', label: 'Left' },
      { value: 'right', label: 'Right' },
      { value: 'top left', label: 'Top Left' },
      { value: 'top right', label: 'Top Right' },
      { value: 'bottom left', label: 'Bottom Left' },
      { value: 'bottom right', label: 'Bottom Right' },
    ],
    tooltip: 'Which part of the image is visible when cropped by object-fit',
  },
  {
    id: 'aspectRatio',
    label: 'Aspect Ratio',
    type: 'dropdown',
    defaultValue: 'auto',
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 4,
    applicableTo: [ComponentType.IMAGE],
    options: [
      { value: 'auto', label: 'Auto' },
      { value: '1/1', label: '1:1 (Square)' },
      { value: '4/3', label: '4:3' },
      { value: '3/2', label: '3:2' },
      { value: '16/9', label: '16:9 (Widescreen)' },
      { value: '21/9', label: '21:9 (Ultrawide)' },
      { value: '3/4', label: '3:4 (Portrait)' },
      { value: '2/3', label: '2:3' },
      { value: '9/16', label: '9:16 (Vertical)' },
    ],
    tooltip: 'Force a specific aspect ratio on the image container',
  },

  // === Loading group ===
  {
    id: 'loading',
    label: 'Loading',
    type: 'dropdown',
    defaultValue: 'lazy',
    group: 'Loading',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 1,
    propertyOrder: 0,
    applicableTo: [ComponentType.IMAGE],
    options: [
      { value: 'lazy', label: 'Lazy' },
      { value: 'eager', label: 'Eager' },
    ],
    tooltip: 'Lazy: loads when near viewport. Eager: loads immediately (use for hero images)',
  },
  {
    id: 'fallbackSrc',
    label: 'Fallback URL',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Loading',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 1,
    propertyOrder: 1,
    applicableTo: [ComponentType.IMAGE],
    tooltip: 'Image URL shown when the primary source fails to load',
    placeholder: 'e.g. https://example.com/fallback.png',
  },
  {
    id: 'placeholder',
    label: 'Placeholder',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Loading',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 1,
    propertyOrder: 2,
    applicableTo: [ComponentType.IMAGE],
    options: [
      { value: 'none', label: 'None' },
      { value: 'skeleton', label: 'Skeleton' },
    ],
    tooltip: 'Show a placeholder animation while the image loads',
  },

  // === Filters group ===
  {
    id: 'filterBlur',
    label: 'Blur',
    type: 'number',
    defaultValue: 0,
    group: 'Filters',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 0,
    applicableTo: [ComponentType.IMAGE],
    tooltip: 'Blur amount in pixels (0 = no blur)',
    validationRules: [{ type: 'range', min: 0, max: 20 }],
  },
  {
    id: 'filterGrayscale',
    label: 'Grayscale',
    type: 'number',
    defaultValue: 0,
    group: 'Filters',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 1,
    applicableTo: [ComponentType.IMAGE],
    tooltip: 'Grayscale percentage (0 = full color, 100 = fully gray)',
    validationRules: [{ type: 'range', min: 0, max: 100 }],
  },
  {
    id: 'filterBrightness',
    label: 'Brightness',
    type: 'number',
    defaultValue: 100,
    group: 'Filters',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 2,
    applicableTo: [ComponentType.IMAGE],
    tooltip: 'Brightness percentage (100 = normal, 0 = black, 200 = double bright)',
    validationRules: [{ type: 'range', min: 0, max: 200 }],
  },

  // === Hover group ===
  {
    id: 'hoverScale',
    label: 'Hover Scale',
    type: 'number',
    defaultValue: 1,
    group: 'Hover',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 3,
    propertyOrder: 0,
    applicableTo: [ComponentType.IMAGE],
    tooltip: 'Scale factor on hover (1 = no change, 1.1 = 10% larger)',
    validationRules: [{ type: 'range', min: 0.5, max: 1.5 }],
  },
  {
    id: 'hoverOpacity',
    label: 'Hover Opacity',
    type: 'number',
    defaultValue: 100,
    group: 'Hover',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 3,
    propertyOrder: 1,
    applicableTo: [ComponentType.IMAGE],
    tooltip: 'Opacity on hover (100 = fully visible, 0 = invisible)',
    validationRules: [{ type: 'range', min: 0, max: 100 }],
  },
  {
    id: 'hoverShadow',
    label: 'Hover Shadow',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Hover',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 3,
    propertyOrder: 2,
    applicableTo: [ComponentType.IMAGE],
    options: [
      { value: 'none', label: 'None' },
      { value: 'sm', label: 'Small' },
      { value: 'md', label: 'Medium' },
      { value: 'lg', label: 'Large' },
      { value: 'xl', label: 'Extra Large' },
    ],
    tooltip: 'Shadow effect on hover',
  },

  // === Events group ===
  {
    id: 'onClick',
    label: 'On Click',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 4,
    propertyOrder: 0,
    applicableTo: [ComponentType.IMAGE],
    tooltip: 'JavaScript expression to execute when the image is clicked',
    placeholder: "e.g. {{ actions.updateVariable('selected', true) }}",
  },

  // === Caption group ===
  {
    id: 'caption',
    label: 'Caption',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Caption',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 5,
    propertyOrder: 0,
    applicableTo: [ComponentType.IMAGE],
    tooltip: 'Caption text displayed below or over the image',
    placeholder: 'e.g. Photo by {{photographer}}',
  },
  {
    id: 'captionPosition',
    label: 'Caption Position',
    type: 'dropdown',
    defaultValue: 'below',
    group: 'Caption',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 5,
    propertyOrder: 1,
    applicableTo: [ComponentType.IMAGE],
    visibleIf: (props: Record<string, any>) => !!(props as any).caption,
    options: [
      { value: 'below', label: 'Below Image' },
      { value: 'overlay-bottom', label: 'Overlay Bottom' },
    ],
    tooltip: 'Where to display the caption relative to the image',
  },
];

/**
 * Image-specific groups
 */
const imageGroups: PropertyGroup[] = [
  { id: 'Basic', label: 'Basic', tab: 'General', order: DEFAULT_GROUP_ORDER['Basic'], collapsible: true },
  { id: 'Loading', label: 'Loading', tab: 'General', order: 1, collapsible: true },
  { id: 'Filters', label: 'Filters', tab: 'General', order: 2, collapsible: true, defaultCollapsed: true },
  { id: 'Hover', label: 'Hover Effects', tab: 'General', order: 3, collapsible: true, defaultCollapsed: true },
  { id: 'Events', label: 'Events', tab: 'General', order: 4, collapsible: true, defaultCollapsed: true },
  { id: 'Caption', label: 'Caption', tab: 'General', order: 5, collapsible: true, defaultCollapsed: true },
];

/**
 * Image property schema
 */
export const imageSchema: ComponentPropertySchema = createPropertySchema(
  ComponentType.IMAGE,
  imageProperties,
  commonTabs,
  [...commonGroups, ...imageGroups]
);
