import { ComponentType } from '../../../types';
import { ComponentPropertySchema, PropertyMetadata, PropertyGroup, PropertyTab } from '../metadata';
import { commonProperties, commonTabs, commonGroups, createPropertySchema, DEFAULT_GROUP_ORDER, formValidationProperties, formAccessibilityProperties, formStateProperties, formGroups } from '../registry';
import { EventsGroupRenderer } from './input-events-renderer';
import { fontSizePresets, fontWeightPresets } from './typographyPresets';

/**
 * Input-specific property definitions
 */
const inputProperties: PropertyMetadata[] = [
  // General Tab - Label (top of Basic group)
  {
    id: 'label',
    label: 'Label',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: -1,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Field label displayed above the input',
    placeholder: 'e.g. First Name',
  },
  // General Tab - Value and Basic Properties
  {
    id: 'value',
    label: 'Value',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Current value of the input (supports expressions).',
    placeholder: 'e.g. {{user.name}} or "John"',
  },
  {
    id: 'defaultValue',
    label: 'Default Value',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Default value for the input field',
    placeholder: 'e.g. {{user.name}} or "John"',
  },
  {
    id: 'placeholder',
    label: 'Placeholder',
    type: 'expression',
    defaultValue: 'Enter text...',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 3,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Placeholder text shown when input is empty',
    placeholder: 'e.g. Enter your name...',
  },
  {
    id: 'inputType',
    label: 'Input Type',
    type: 'dropdown',
    defaultValue: 'text',
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 4,
    applicableTo: [ComponentType.INPUT],
    options: [
      { value: 'text', label: 'Text' },
      { value: 'number', label: 'Number' },
      { value: 'password', label: 'Password' },
      { value: 'email', label: 'Email' },
      { value: 'url', label: 'URL' },
      { value: 'tel', label: 'Telephone' },
    ],
    tooltip: 'HTML input type',
  },
  
  // Validation properties moved to General tab
  {
    id: 'required',
    label: 'Required',
    type: 'expression',
    defaultValue: false,
    supportsExpression: true,
    group: 'Validation',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 0,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Whether the input is required',
    placeholder: 'e.g. true or {{someCondition}}',
  },
  {
    id: 'max',
    label: 'Max Value',
    type: 'expression',
    defaultValue: undefined,
    supportsExpression: true,
    group: 'Validation',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 2,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Maximum value (for number inputs, supports expressions)',
    placeholder: 'e.g. 100 or {{maxValue}}',
    visibleIf: (props) => (props as any).inputType === 'number',
  },
  {
    id: 'pattern',
    label: 'Regex Pattern',
    type: 'string',
    defaultValue: '',
    group: 'Validation',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 4,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Regular expression pattern for validation',
    placeholder: 'e.g. [A-Za-z]+',
    presets: [
      { label: 'Email', value: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$' },
      { label: 'Phone', value: '^[\\d\\-\\+\\(\\)\\s]{7,20}$' },
      { label: 'URL', value: '^https?:\\/\\/.+' },
      { label: 'Alphanumeric', value: '^[A-Za-z0-9]+$' },
      { label: 'Numbers only', value: '^\\d+$' },
      { label: 'Letters only', value: '^[A-Za-z]+$' },
    ],
  },
  {
    id: 'maxLength',
    label: 'Max Length',
    type: 'number',
    defaultValue: 0,
    group: 'Validation',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 5,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Maximum number of characters allowed',
  },
  {
    id: 'errorMessage',
    label: 'Error Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Validation',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 6,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Custom error message for all validation rules (required, regex pattern, max length)',
    placeholder: 'e.g. "Please enter a valid email" or {{customError}}',
    helpText: 'Applies to all validation rules (required, regex, max length)',
  },
  
  // Layout properties - use common properties (x, y, width, height from commonProperties)
  // Only add zIndex as a custom property in General tab Layout group
  {
    id: 'zIndex',
    label: 'Z-Index',
    type: 'expression',
    defaultValue: undefined,
    supportsExpression: true,
    group: 'Layout',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 1,
    propertyOrder: 4,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Z-index for layering components (supports expressions)',
    placeholder: 'e.g. 1, 10, 100 or {{zIndex}}',
  },
  
  // Styles Tab - Typography
  {
    id: 'fontSize',
    label: 'Font Size',
    type: 'dropdown',
    defaultValue: '{{theme.typography.fontSizeMd}}',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Font size - select a scale preset or enter a custom value',
    placeholder: 'e.g. 14px or {{theme.typography.fontSizeMd}}',
    options: fontSizePresets,
    allowCustom: true,
  },
  {
    id: 'fontFamily',
    label: 'Font Family',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Font family name',
    placeholder: 'e.g. Arial, sans-serif',
  },
  {
    id: 'fontWeight',
    label: 'Font Weight',
    type: 'dropdown',
    defaultValue: '{{theme.typography.fontWeightNormal}}',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Font weight - select a preset or enter a custom value',
    placeholder: 'e.g. bold or 600',
    options: fontWeightPresets,
    allowCustom: true,
  },
  {
    id: 'fontStyle',
    label: 'Font Style',
    type: 'dropdown',
    defaultValue: 'normal',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 3,
    applicableTo: [ComponentType.INPUT],
    options: [
      { value: 'normal', label: 'Normal' },
      { value: 'italic', label: 'Italic' },
    ],
    tooltip: 'Font style',
  },
  {
    id: 'textAlign',
    label: 'Text Align',
    type: 'dropdown',
    defaultValue: 'left',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 4,
    applicableTo: [ComponentType.INPUT],
    options: [
      { value: 'left', label: 'Left' },
      { value: 'center', label: 'Center' },
      { value: 'right', label: 'Right' },
    ],
    tooltip: 'Text alignment',
  },
  {
    id: 'color',
    label: 'Text Color',
    type: 'color',
    defaultValue: '#111827',
    supportsExpression: true,
    group: 'Color',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 0,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Text color',
  },
  {
    id: 'backgroundColor',
    label: 'Background Color',
    type: 'color',
    defaultValue: '#ffffff',
    supportsExpression: true,
    group: 'Color',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 1,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Background color',
  },
  
  // Events Tab
  {
    id: 'onChangeActionType',
    label: 'On Change Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.INPUT],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when input value changes',
  },
  {
    id: 'onChangeAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.INPUT],
    visibleIf: (props) => (props as any).onChangeActionType === 'alert',
    tooltip: 'Message to display in alert (supports expressions)',
    placeholder: 'e.g., {{ "Value changed: " + event.target.value }}',
  },
  {
    id: 'onChangeCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.INPUT],
    visibleIf: (props) => (props as any).onChangeActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when input value changes',
    placeholder: 'e.g., {{ (() => { console.log(event.target.value); })() }}',
  },
  // On Focus Action
  {
    id: 'onFocusActionType',
    label: 'On Focus Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 10,
    applicableTo: [ComponentType.INPUT],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when input gains focus',
  },
  {
    id: 'onFocusAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 11,
    applicableTo: [ComponentType.INPUT],
    visibleIf: (props) => (props as any).onFocusActionType === 'alert',
    tooltip: 'Message to display in alert when input gains focus (supports expressions)',
    placeholder: 'e.g., {{ "Input focused" }}',
  },
  {
    id: 'onFocusCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 12,
    applicableTo: [ComponentType.INPUT],
    visibleIf: (props) => (props as any).onFocusActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when input gains focus',
    placeholder: 'e.g., {{ (() => { console.log("Focused"); })() }}',
  },
  // On Blur Action
  {
    id: 'onBlurActionType',
    label: 'On Blur Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 20,
    applicableTo: [ComponentType.INPUT],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when input loses focus',
  },
  {
    id: 'onBlurAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 21,
    applicableTo: [ComponentType.INPUT],
    visibleIf: (props) => (props as any).onBlurActionType === 'alert',
    tooltip: 'Message to display in alert when input loses focus (supports expressions)',
    placeholder: 'e.g., {{ "Input blurred" }}',
  },
  {
    id: 'onBlurCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 22,
    applicableTo: [ComponentType.INPUT],
    visibleIf: (props) => (props as any).onBlurActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when input loses focus',
    placeholder: 'e.g., {{ (() => { console.log("Blurred"); })() }}',
  },
  // On Enter Key Press Action
  {
    id: 'onEnterActionType',
    label: 'On Enter Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 30,
    applicableTo: [ComponentType.INPUT],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when Enter key is pressed',
  },
  {
    id: 'onEnterAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 31,
    applicableTo: [ComponentType.INPUT],
    visibleIf: (props) => (props as any).onEnterActionType === 'alert',
    tooltip: 'Message to display in alert when Enter key is pressed (supports expressions)',
    placeholder: 'e.g., {{ "Enter key pressed" }}',
  },
  {
    id: 'onEnterCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 32,
    applicableTo: [ComponentType.INPUT],
    visibleIf: (props) => (props as any).onEnterActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when Enter key is pressed',
    placeholder: 'e.g., {{ (() => { console.log("Enter pressed"); })() }}',
  },
  
  // Appearance group
  {
    id: 'prefixText',
    label: 'Prefix Text',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Appearance',
    tab: 'General',
    tabOrder: 0,
    groupOrder: DEFAULT_GROUP_ORDER['Appearance'],
    propertyOrder: 1,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Text displayed before the input (e.g. $, http://)',
    placeholder: 'e.g. $',
  },
  {
    id: 'suffixText',
    label: 'Suffix Text',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Appearance',
    tab: 'General',
    tabOrder: 0,
    groupOrder: DEFAULT_GROUP_ORDER['Appearance'],
    propertyOrder: 2,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Text displayed after the input (e.g. .com, kg)',
    placeholder: 'e.g. .com',
  },
  {
    id: 'clearButton',
    label: 'Clear Button',
    type: 'boolean',
    defaultValue: false,
    group: 'Appearance',
    tab: 'General',
    tabOrder: 0,
    groupOrder: DEFAULT_GROUP_ORDER['Appearance'],
    propertyOrder: 3,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Show clear button when input has a value',
  },
  {
    id: 'showCharacterCount',
    label: 'Character Count',
    type: 'boolean',
    defaultValue: false,
    group: 'Appearance',
    tab: 'General',
    tabOrder: 0,
    groupOrder: DEFAULT_GROUP_ORDER['Appearance'],
    propertyOrder: 4,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Show character count (requires Max Length to be set)',
  },
  {
    id: 'textTransform',
    label: 'Text Transform',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Appearance',
    tab: 'General',
    tabOrder: 0,
    groupOrder: DEFAULT_GROUP_ORDER['Appearance'],
    propertyOrder: 5,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Transform text casing',
    options: [
      { value: 'none', label: 'None' },
      { value: 'uppercase', label: 'Uppercase' },
      { value: 'lowercase', label: 'Lowercase' },
      { value: 'capitalize', label: 'Capitalize' },
    ],
  },
  {
    id: 'autoComplete',
    label: 'Autocomplete',
    type: 'dropdown',
    defaultValue: 'off',
    group: 'Appearance',
    tab: 'General',
    tabOrder: 0,
    groupOrder: DEFAULT_GROUP_ORDER['Appearance'],
    propertyOrder: 6,
    applicableTo: [ComponentType.INPUT],
    tooltip: 'Browser autocomplete hint',
    options: [
      { value: 'off', label: 'Off' },
      { value: 'on', label: 'On' },
      { value: 'name', label: 'Name' },
      { value: 'email', label: 'Email' },
      { value: 'tel', label: 'Telephone' },
      { value: 'url', label: 'URL' },
      { value: 'username', label: 'Username' },
      { value: 'current-password', label: 'Password' },
    ],
  },
  // Spread shared form properties
  ...formValidationProperties.map(p => ({ ...p, applicableTo: [ComponentType.INPUT] as any })),
  ...formAccessibilityProperties.map(p => ({
    ...p,
    applicableTo: [ComponentType.INPUT] as any,
    defaultValue: p.id === 'accessibilityLabel' ? 'Text input field' : p.defaultValue,
  })),
  ...formStateProperties.map(p => ({ ...p, applicableTo: [ComponentType.INPUT] as any })),
];

/**
 * Input-specific tabs - only General, Styles, and Events
 */
const inputTabs: PropertyTab[] = [
  { id: 'General', label: 'General', order: 0 },
  { id: 'Styles', label: 'Styles', order: 1 },
  { id: 'Events', label: 'Events', order: 2 },
];


/**
 * Input-specific groups
 */
const inputGroups: PropertyGroup[] = [
  {
    id: 'Basic',
    label: 'Basic',
    tab: 'General',
    order: DEFAULT_GROUP_ORDER['Basic'],
    collapsible: true,
    defaultCollapsed: false
  },
  { id: 'Validation', label: 'Validation', tab: 'General', collapsible: true, defaultCollapsed: false },
  { id: 'Appearance', label: 'Appearance', tab: 'General', collapsible: true, defaultCollapsed: false },
  { id: 'Typography', label: 'Typography', tab: 'Styles', collapsible: true, defaultCollapsed: false },
  { id: 'Color', label: 'Color', tab: 'Styles', collapsible: true, defaultCollapsed: false },
  {
    id: 'Events',
    label: 'Events',
    tab: 'Events',
    collapsible: true,
    defaultCollapsed: false,
    customGroupRenderer: EventsGroupRenderer,
  },
  { id: 'Advanced', label: 'Advanced', tab: 'Styles', collapsible: true, defaultCollapsed: true },
  { id: 'Accessibility', label: 'Accessibility', tab: 'General', collapsible: true, defaultCollapsed: true },
];

/**
 * Input property schema
 */
export const inputSchema: ComponentPropertySchema = createPropertySchema(
  ComponentType.INPUT,
  inputProperties,
  inputTabs,
  [...commonGroups, ...inputGroups]
);
