import { ComponentType } from '../../../types';
import { ComponentPropertySchema, PropertyMetadata, PropertyGroup } from '../metadata';
import { commonProperties, commonTabs, commonGroups, createPropertySchema } from '../registry';
import { fontSizePresets, fontWeightPresets } from './typographyPresets';

/**
 * Label-specific property definitions
 */
const labelProperties: PropertyMetadata[] = [
  {
    id: 'text',
    label: 'Text',
    type: 'expression',
    defaultValue: 'New Label',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.LABEL],
    tooltip: 'Label text content',
    placeholder: 'e.g. Enter your name...',
  },
  {
    id: 'fontSize',
    label: 'Font Size',
    type: 'dropdown',
    defaultValue: '{{theme.typography.fontSizeMd}}',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.LABEL],
    tooltip: 'Font size - select a scale preset or enter a custom value',
    placeholder: 'e.g. 16px or {{theme.typography.fontSizeLg}}',
    options: fontSizePresets,
    allowCustom: true,
  },
  {
    id: 'fontWeight',
    label: 'Font Weight',
    type: 'dropdown',
    defaultValue: '{{theme.typography.fontWeightNormal}}',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.LABEL],
    tooltip: 'Font weight - select a preset or enter a custom value',
    placeholder: 'e.g. bold or 600',
    options: fontWeightPresets,
    allowCustom: true,
  },
  {
    id: 'color',
    label: 'Text Color',
    type: 'color',
    defaultValue: '#111827',
    supportsExpression: true,
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.LABEL],
    tooltip: 'Text color',
  },
  {
    id: 'textAlign',
    label: 'Text Align',
    type: 'dropdown',
    defaultValue: 'left',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 3,
    applicableTo: [ComponentType.LABEL],
    options: [
      { value: 'left', label: 'Left' },
      { value: 'center', label: 'Center' },
      { value: 'right', label: 'Right' },
    ],
    tooltip: 'Text alignment',
  },
  {
    id: 'fontFamily',
    label: 'Font Family',
    type: 'expression',
    defaultValue: 'sans-serif',
    supportsExpression: true,
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 4,
    applicableTo: [ComponentType.LABEL],
    tooltip: 'Font family',
    placeholder: 'e.g. Arial, sans-serif',
  },
  {
    id: 'backgroundColor',
    label: 'Background Color',
    type: 'color',
    defaultValue: 'transparent',
    supportsExpression: true,
    group: 'Styling',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.LABEL],
    tooltip: 'Background color',
  },
  {
    id: 'textRenderer',
    label: 'Text Renderer',
    type: 'dropdown',
    defaultValue: 'javascript',
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.LABEL],
    options: [
      { value: 'javascript', label: 'JavaScript' },
      { value: 'markdown', label: 'Markdown' },
      { value: 'literal', label: 'Literal' },
    ],
    tooltip: 'How to render the text content',
  },
  {
    id: 'lineHeight',
    label: 'Line Height',
    type: 'expression',
    defaultValue: undefined,
    supportsExpression: true,
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 5,
    applicableTo: [ComponentType.LABEL],
    tooltip: 'Line height (e.g., 1.5, 24px, 150%)',
    placeholder: 'e.g. 1.6 or {{theme.typography.lineHeightNormal}}',
  },
  {
    id: 'letterSpacing',
    label: 'Letter Spacing',
    type: 'expression',
    defaultValue: undefined,
    supportsExpression: true,
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 6,
    applicableTo: [ComponentType.LABEL],
    tooltip: 'Space between characters',
    placeholder: 'e.g. 0.5px or -0.02em',
  },
  {
    id: 'textTransform',
    label: 'Text Transform',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 7,
    applicableTo: [ComponentType.LABEL],
    options: [
      { value: 'none', label: 'None' },
      { value: 'uppercase', label: 'UPPERCASE' },
      { value: 'lowercase', label: 'lowercase' },
      { value: 'capitalize', label: 'Capitalize' },
    ],
    tooltip: 'Text case transformation',
  },
  {
    id: 'textDecoration',
    label: 'Text Decoration',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 8,
    applicableTo: [ComponentType.LABEL],
    options: [
      { value: 'none', label: 'None' },
      { value: 'underline', label: 'Underline' },
      { value: 'line-through', label: 'Strikethrough' },
    ],
    tooltip: 'Text decoration',
  },
  {
    id: 'cursor',
    label: 'Cursor',
    type: 'dropdown',
    defaultValue: 'default',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 9,
    applicableTo: [ComponentType.LABEL],
    options: [
      { value: 'default', label: 'Default' },
      { value: 'pointer', label: 'Pointer (hand)' },
      { value: 'text', label: 'Text (I-beam)' },
      { value: 'not-allowed', label: 'Not Allowed' },
    ],
    tooltip: 'Mouse cursor style on hover',
  },
  {
    id: 'href',
    label: 'Link URL',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.LABEL],
    tooltip: 'Navigate to URL on click. Use https://... for external, page_xxx for internal pages, or #anchorId for scroll-to-section.',
    placeholder: 'e.g. https://example.com or #section1',
  },
];

/**
 * Label-specific groups
 * Order values use DEFAULT_GROUP_ORDER from registry for consistency
 */
const labelGroups: PropertyGroup[] = [
  { id: 'Basic', label: 'Basic', tab: 'General', collapsible: true, defaultCollapsed: false },
  { id: 'Typography', label: 'Typography', tab: 'Styles', collapsible: true, defaultCollapsed: false },
];

/**
 * Label property schema
 */
export const labelSchema: ComponentPropertySchema = createPropertySchema(
  ComponentType.LABEL,
  labelProperties,
  commonTabs,
  [...commonGroups, ...labelGroups]
);

