import { ComponentType } from '../../../types';
import { PropertyMetadata } from '../metadata';
import { createPropertySchema } from '../registry';
import { fontSizePresets, fontWeightPresets } from './typographyPresets';

export const labelProperties: PropertyMetadata[] = [
  {
    id: 'text',
    label: 'Text',
    type: 'expression',
    defaultValue: 'Label',
    supportsExpression: true,
    group: 'Content',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 0,
    applicableTo: [ComponentType.LABEL],
    tooltip: 'Label text content',
  },
  {
    id: 'fontSize',
    label: 'Font Size',
    type: 'dropdown',
    defaultValue: '{{theme.typography.fontSizeMd}}',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 0,
    applicableTo: [ComponentType.LABEL],
    tooltip: 'Font size - select a scale preset or enter a custom value',
    placeholder: 'e.g. 16px or {{theme.typography.fontSizeLg}}',
    options: fontSizePresets,
    allowCustom: true,
  },
  {
    id: 'fontWeight',
    label: 'Font Weight',
    type: 'dropdown',
    defaultValue: '{{theme.typography.fontWeightNormal}}',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 1,
    applicableTo: [ComponentType.LABEL],
    tooltip: 'Font weight - select a preset or enter a custom value',
    placeholder: 'e.g. bold or 600',
    options: fontWeightPresets,
    allowCustom: true,
  },
  {
    id: 'color',
    label: 'Text Color',
    type: 'color',
    defaultValue: '#111827',
    supportsExpression: true,
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 2,
    applicableTo: [ComponentType.LABEL],
  },
  {
    id: 'textAlign',
    label: 'Text Align',
    type: 'dropdown',
    defaultValue: 'left',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 3,
    applicableTo: [ComponentType.LABEL],
    options: [
      { value: 'left', label: 'Left' },
      { value: 'center', label: 'Center' },
      { value: 'right', label: 'Right' },
    ],
  },
  {
    id: 'fontFamily',
    label: 'Font Family',
    type: 'string',
    defaultValue: '',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 4,
    applicableTo: [ComponentType.LABEL],
  },
  {
    id: 'backgroundColor',
    label: 'Background Color',
    type: 'color',
    defaultValue: 'transparent',
    supportsExpression: true,
    group: 'Background',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.LABEL],
  },
];

export const labelSchema = createPropertySchema(ComponentType.LABEL, labelProperties);



