import { ComponentType } from '../../../types';
import { ComponentPropertySchema, PropertyMetadata, PropertyGroup, PropertyTab } from '../metadata';
import { commonProperties, commonTabs, commonGroups, createPropertySchema, DEFAULT_GROUP_ORDER, formValidationProperties, formAccessibilityProperties, formStateProperties, formGroups } from '../registry';
import { SharedEventsGroupRenderer } from './shared-events-renderer';
import { fontSizePresets, fontWeightPresets } from './typographyPresets';

/**
 * Select-specific property definitions
 */
const selectProperties: PropertyMetadata[] = [
  {
    id: 'label',
    label: 'Label',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: -1,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'Field label displayed above the select',
    placeholder: 'e.g. Country',
  },
  {
    id: 'placeholder',
    label: 'Placeholder',
    type: 'expression',
    defaultValue: 'Select an option',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'Placeholder text shown when no option is selected',
    placeholder: 'e.g. Choose an option...',
  },
  {
    id: 'options',
    label: 'Options',
    type: 'string',
    defaultValue: 'Option 1,Option 2,Option 3',
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'Comma-separated list of options',
    placeholder: 'e.g. Option 1,Option 2,Option 3',
  },
  {
    id: 'defaultValue',
    label: 'Default Value',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'Initial selected value',
  },
  {
    id: 'value',
    label: 'Value',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 3,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'Current value binding (supports expressions)',
    placeholder: 'e.g. {{selectedOption}} or "Option 1"',
  },
  {
    id: 'accessibilityLabel',
    label: 'Accessibility Label',
    type: 'string',
    defaultValue: 'Dropdown select',
    group: 'Accessibility',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 3,
    propertyOrder: 0,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'A descriptive label for screen readers',
    placeholder: 'A descriptive label for screen readers',
  },
  // Appearance group
  {
    id: 'multiple',
    label: 'Multiple Select',
    type: 'boolean',
    defaultValue: false,
    group: 'Appearance',
    tab: 'General',
    tabOrder: 0,
    groupOrder: DEFAULT_GROUP_ORDER['Appearance'],
    propertyOrder: 1,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'Allow selecting multiple options',
  },
  {
    id: 'clearable',
    label: 'Clearable',
    type: 'boolean',
    defaultValue: false,
    group: 'Appearance',
    tab: 'General',
    tabOrder: 0,
    groupOrder: DEFAULT_GROUP_ORDER['Appearance'],
    propertyOrder: 2,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'Show clear button to reset selection',
  },
  {
    id: 'searchable',
    label: 'Searchable',
    type: 'boolean',
    defaultValue: false,
    group: 'Appearance',
    tab: 'General',
    tabOrder: 0,
    groupOrder: DEFAULT_GROUP_ORDER['Appearance'],
    propertyOrder: 3,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'Enable search/filter within options',
  },
  // Spread shared form properties
  ...formValidationProperties.map(p => ({ ...p, applicableTo: [ComponentType.SELECT] as any })),
  ...formAccessibilityProperties.map(p => ({
    ...p,
    applicableTo: [ComponentType.SELECT] as any,
    defaultValue: p.id === 'accessibilityLabel' ? 'Dropdown select' : p.defaultValue,
  })),
  ...formStateProperties.map(p => ({ ...p, applicableTo: [ComponentType.SELECT] as any })),
  // Layout properties - zIndex
  {
    id: 'zIndex',
    label: 'Z-Index',
    type: 'expression',
    defaultValue: undefined,
    supportsExpression: true,
    group: 'Layout',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 1,
    propertyOrder: 4,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'Z-index for layering components (supports expressions)',
    placeholder: 'e.g. 1, 10, 100 or {{zIndex}}',
  },
  // Styles Tab - Typography
  {
    id: 'fontSize',
    label: 'Font Size',
    type: 'dropdown',
    defaultValue: '{{theme.typography.fontSizeMd}}',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'Font size - select a scale preset or enter a custom value',
    placeholder: 'e.g. 14px or {{theme.typography.fontSizeMd}}',
    options: fontSizePresets,
    allowCustom: true,
  },
  {
    id: 'fontFamily',
    label: 'Font Family',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'Font family name',
    placeholder: 'e.g. Arial, sans-serif',
  },
  {
    id: 'fontWeight',
    label: 'Font Weight',
    type: 'dropdown',
    defaultValue: '{{theme.typography.fontWeightNormal}}',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'Font weight - select a preset or enter a custom value',
    placeholder: 'e.g. bold or 600',
    options: fontWeightPresets,
    allowCustom: true,
  },
  {
    id: 'fontStyle',
    label: 'Font Style',
    type: 'dropdown',
    defaultValue: 'normal',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 3,
    applicableTo: [ComponentType.SELECT],
    options: [
      { value: 'normal', label: 'Normal' },
      { value: 'italic', label: 'Italic' },
    ],
    tooltip: 'Font style',
  },
  // Styles Tab - Color
  {
    id: 'color',
    label: 'Text Color',
    type: 'color',
    defaultValue: '#111827',
    supportsExpression: true,
    group: 'Color',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 0,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'Text color',
  },
  {
    id: 'backgroundColor',
    label: 'Background Color',
    type: 'color',
    defaultValue: '#ffffff',
    supportsExpression: true,
    group: 'Color',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 1,
    applicableTo: [ComponentType.SELECT],
    tooltip: 'Background color',
  },
  // Events Tab
  {
    id: 'onChangeActionType',
    label: 'On Change Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.SELECT],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when select value changes',
  },
  {
    id: 'onChangeAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.SELECT],
    visibleIf: (props) => (props as any).onChangeActionType === 'alert',
    tooltip: 'Message to display in alert (supports expressions)',
    placeholder: 'e.g., {{ "Value changed: " + event.target.value }}',
  },
  {
    id: 'onChangeCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.SELECT],
    visibleIf: (props) => (props as any).onChangeActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when select value changes',
    placeholder: 'e.g., {{ (() => { console.log(event.target.value); })() }}',
  },
  // On Focus Action
  {
    id: 'onFocusActionType',
    label: 'On Focus Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 10,
    applicableTo: [ComponentType.SELECT],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when select gains focus',
  },
  {
    id: 'onFocusAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 11,
    applicableTo: [ComponentType.SELECT],
    visibleIf: (props) => (props as any).onFocusActionType === 'alert',
    tooltip: 'Message to display in alert when select gains focus (supports expressions)',
    placeholder: 'e.g., {{ "Select focused" }}',
  },
  {
    id: 'onFocusCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 12,
    applicableTo: [ComponentType.SELECT],
    visibleIf: (props) => (props as any).onFocusActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when select gains focus',
    placeholder: 'e.g., {{ (() => { console.log("Focused"); })() }}',
  },
  // On Blur Action
  {
    id: 'onBlurActionType',
    label: 'On Blur Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 20,
    applicableTo: [ComponentType.SELECT],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when select loses focus',
  },
  {
    id: 'onBlurAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 21,
    applicableTo: [ComponentType.SELECT],
    visibleIf: (props) => (props as any).onBlurActionType === 'alert',
    tooltip: 'Message to display in alert when select loses focus (supports expressions)',
    placeholder: 'e.g., {{ "Select blurred" }}',
  },
  {
    id: 'onBlurCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 22,
    applicableTo: [ComponentType.SELECT],
    visibleIf: (props) => (props as any).onBlurActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when select loses focus',
    placeholder: 'e.g., {{ (() => { console.log("Blurred"); })() }}',
  },
  // On Enter Key Press Action
  {
    id: 'onEnterActionType',
    label: 'On Enter Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 30,
    applicableTo: [ComponentType.SELECT],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when Enter key is pressed',
  },
  {
    id: 'onEnterAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 31,
    applicableTo: [ComponentType.SELECT],
    visibleIf: (props) => (props as any).onEnterActionType === 'alert',
    tooltip: 'Message to display in alert when Enter key is pressed (supports expressions)',
    placeholder: 'e.g., {{ "Enter key pressed" }}',
  },
  {
    id: 'onEnterCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 32,
    applicableTo: [ComponentType.SELECT],
    visibleIf: (props) => (props as any).onEnterActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when Enter key is pressed',
    placeholder: 'e.g., {{ (() => { console.log("Enter pressed"); })() }}',
  },
];

/**
 * Select-specific tabs - General, Styles, and Events
 */
const selectTabs: PropertyTab[] = [
  { id: 'General', label: 'General', order: 0 },
  { id: 'Styles', label: 'Styles', order: 1 },
  { id: 'Events', label: 'Events', order: 2 },
];

/**
 * Select-specific groups
 * Note: Layout, State, and Styling are already in commonGroups, so we don't duplicate them
 * Order values use DEFAULT_GROUP_ORDER from registry for consistency
 */
const selectGroups: PropertyGroup[] = [
  { id: 'Basic', label: 'Basic', tab: 'General', order: DEFAULT_GROUP_ORDER['Basic'], collapsible: true, defaultCollapsed: false },
  { id: 'Validation', label: 'Validation', tab: 'General', collapsible: true, defaultCollapsed: false },
  { id: 'Appearance', label: 'Appearance', tab: 'General', collapsible: true, defaultCollapsed: false },
  { id: 'Accessibility', label: 'Accessibility', tab: 'General', order: DEFAULT_GROUP_ORDER['Accessibility'], collapsible: true, defaultCollapsed: true },
  { id: 'Typography', label: 'Typography', tab: 'Styles', collapsible: true, defaultCollapsed: false },
  { id: 'Color', label: 'Color', tab: 'Styles', collapsible: true, defaultCollapsed: false },
  { id: 'Advanced', label: 'Advanced', tab: 'Styles', collapsible: true, defaultCollapsed: true },
  {
    id: 'Events',
    label: 'Events',
    tab: 'Events',
    collapsible: true,
    defaultCollapsed: false,
    customGroupRenderer: SharedEventsGroupRenderer,
  },
];

/**
 * Select property schema
 */
export const selectSchema: ComponentPropertySchema = createPropertySchema(
  ComponentType.SELECT,
  selectProperties,
  selectTabs,
  [...commonGroups, ...selectGroups]
);

