import { ComponentType } from '../../../types';
import { ComponentPropertySchema, PropertyMetadata, PropertyGroup } from '../metadata';
import { commonProperties, commonTabs, commonGroups, createPropertySchema } from '../registry';
import { fontSizePresets } from './typographyPresets';

/**
 * Table-specific property definitions
 */
const tableProperties: PropertyMetadata[] = [
  // --- Data group ---
  {
    id: 'data',
    label: 'Data Source',
    type: 'expression',
    defaultValue: '{{[]}}',
    supportsExpression: true,
    group: 'Data',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 10,
    propertyOrder: 0,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Expression that evaluates to an array of objects (e.g., {{dataStore.users}})',
    placeholder: 'e.g. {{dataStore.users}}',
  },
  {
    id: 'emptyStateText',
    label: 'Empty State Text',
    type: 'string',
    defaultValue: 'No records found',
    group: 'Data',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 10,
    propertyOrder: 1,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Text displayed when the table has no data',
    placeholder: 'e.g. No records found',
  },
  {
    id: 'sampleData',
    label: 'Sample Data',
    type: 'code',
    defaultValue: '',
    group: 'Data',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 10,
    propertyOrder: 2,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'JSON array for testing (e.g., [{"name":"John","age":30}])',
    placeholder: '[{"name":"John","age":30},{"name":"Jane","age":25}]',
  },

  // --- Columns group ---
  {
    id: 'columns',
    label: 'Columns',
    type: 'string',
    defaultValue: 'Name:name,Email:email,Role:role',
    group: 'Columns',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 11,
    propertyOrder: 0,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Column definitions in format: Header:key,Header2:key2',
    placeholder: 'e.g. Name:name,Email:email,Role:role',
  },

  // --- Sorting & Filtering group ---
  {
    id: 'sortableColumns',
    label: 'Sortable Columns',
    type: 'string',
    defaultValue: '',
    group: 'Sorting & Filtering',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 12,
    propertyOrder: 0,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Comma-separated column keys that can be sorted, or "*" for all',
    placeholder: 'e.g. name,email or *',
  },
  {
    id: 'filterableColumns',
    label: 'Filterable Columns',
    type: 'string',
    defaultValue: '',
    group: 'Sorting & Filtering',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 12,
    propertyOrder: 1,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Comma-separated column keys that are searchable, or "*" for all',
    placeholder: 'e.g. name,email or *',
  },
  {
    id: 'showSearch',
    label: 'Show Search Bar',
    type: 'boolean',
    defaultValue: false,
    group: 'Sorting & Filtering',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 12,
    propertyOrder: 2,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Show a global search bar above the table',
  },
  {
    id: 'searchPlaceholder',
    label: 'Search Placeholder',
    type: 'string',
    defaultValue: 'Search...',
    group: 'Sorting & Filtering',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 12,
    propertyOrder: 3,
    applicableTo: [ComponentType.TABLE],
    visibleIf: (props) => (props as any).showSearch === true,
    tooltip: 'Placeholder text for the search input',
    placeholder: 'e.g. Search...',
  },

  // --- Row Selection group ---
  {
    id: 'rowSelectAction',
    label: 'Row Select Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'On Row Select',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 13,
    propertyOrder: 0,
    applicableTo: [ComponentType.TABLE],
    options: [
      { value: 'none', label: 'None' },
      { value: 'updateDataStore', label: 'Update Data Store' },
    ],
    tooltip: 'Action to perform when a row is clicked',
  },
  {
    id: 'selectedRecordKey',
    label: 'Selected Record Key',
    type: 'string',
    defaultValue: 'selectedRecord',
    group: 'On Row Select',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 13,
    propertyOrder: 1,
    applicableTo: [ComponentType.TABLE],
    visibleIf: (props) => (props as any).rowSelectAction === 'updateDataStore',
    tooltip: 'Key in dataStore where selected record is saved',
    placeholder: 'e.g. selectedRecord',
  },

  // --- Table Appearance group (Styles tab) ---
  {
    id: 'resizable',
    label: 'Resizable Columns',
    type: 'boolean',
    defaultValue: true,
    group: 'Table Appearance',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 0,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Enable column resize by dragging column borders',
  },
  {
    id: 'rowHeight',
    label: 'Row Height',
    type: 'number',
    defaultValue: 40,
    group: 'Table Appearance',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 1,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Fixed row height in pixels (used for virtualization)',
    placeholder: 'e.g. 40',
  },
  {
    id: 'stickyHeader',
    label: 'Sticky Header',
    type: 'boolean',
    defaultValue: true,
    group: 'Table Appearance',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 2,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Keep the header fixed when scrolling',
  },
  {
    id: 'striped',
    label: 'Striped Rows',
    type: 'boolean',
    defaultValue: false,
    group: 'Table Appearance',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 3,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Alternating row background colors',
  },
  {
    id: 'stripedColor',
    label: 'Stripe Color',
    type: 'color',
    defaultValue: '#f9fafb',
    supportsExpression: true,
    group: 'Table Appearance',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 4,
    applicableTo: [ComponentType.TABLE],
    visibleIf: (props) => (props as any).striped === true,
    tooltip: 'Background color for alternating rows',
  },
  {
    id: 'showRowNumbers',
    label: 'Show Row Numbers',
    type: 'boolean',
    defaultValue: false,
    group: 'Table Appearance',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 5,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Show a row number column',
  },
  {
    id: 'headerBackgroundColor',
    label: 'Header Background',
    type: 'color',
    defaultValue: '',
    supportsExpression: true,
    group: 'Table Appearance',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 6,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Background color of the table header row',
  },
  {
    id: 'rowBorderColor',
    label: 'Row Border Color',
    type: 'color',
    defaultValue: '',
    supportsExpression: true,
    group: 'Table Appearance',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 7,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Border color between table rows',
  },
  {
    id: 'fontSize',
    label: 'Font Size',
    type: 'dropdown',
    defaultValue: '',
    group: 'Table Appearance',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 8,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Font size - select a scale preset or enter a custom value',
    placeholder: 'e.g. 14px or {{theme.typography.fontSizeSm}}',
    options: fontSizePresets,
    allowCustom: true,
  },
  {
    id: 'color',
    label: 'Text Color',
    type: 'color',
    defaultValue: '',
    supportsExpression: true,
    group: 'Table Appearance',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 9,
    applicableTo: [ComponentType.TABLE],
    tooltip: 'Text color for table content',
  },
];

/**
 * Table-specific groups
 */
const tableGroups: PropertyGroup[] = [
  { id: 'Data', label: 'Data', tab: 'General', order: 10, collapsible: true, defaultCollapsed: false },
  { id: 'Columns', label: 'Columns', tab: 'General', order: 11, collapsible: true, defaultCollapsed: false },
  { id: 'Sorting & Filtering', label: 'Sorting & Filtering', tab: 'General', order: 12, collapsible: true, defaultCollapsed: false },
  { id: 'On Row Select', label: 'On Row Select', tab: 'General', order: 13, collapsible: true, defaultCollapsed: false },
  { id: 'Table Appearance', label: 'Table Appearance', tab: 'Styles', order: 1, collapsible: true, defaultCollapsed: false },
];

/**
 * Table property schema
 */
export const tableSchema: ComponentPropertySchema = createPropertySchema(
  ComponentType.TABLE,
  tableProperties,
  commonTabs,
  [...commonGroups, ...tableGroups]
);
