import { ComponentType } from '@/types';
import { ComponentTemplate } from '../types';

export const cardTemplate: ComponentTemplate = {
  id: 'card',
  name: 'Card',
  description: 'Content card with image, title, description, and action button',
  icon: 'Square',
  components: [
    {
      type: ComponentType.CONTAINER,
      name: 'Card',
      props: {
        width: '320px',
        height: 'auto',
        backgroundColor: '{{theme.colors.surface}}',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'stretch',
        gap: '0px',
        padding: '0px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: '{{theme.colors.border}}',
        borderRadius: '{{theme.radius.lg}}',
        boxShadow: '{{theme.shadow.sm}}',
        overflow: 'hidden',
      },
      children: [
        {
          type: ComponentType.IMAGE,
          name: 'Card Image',
          props: {
            src: 'https://picsum.photos/400/240',
            alt: 'Card image',
            width: '100%',
            height: 200,
            objectFit: 'cover',
            borderRadius: '0px',
          },
        },
        {
          type: ComponentType.CONTAINER,
          name: 'Card Content',
          props: {
            width: '100%',
            height: 'auto',
            backgroundColor: 'transparent',
            flexDirection: 'column',
            justifyContent: 'flex-start',
            alignItems: 'flex-start',
            gap: '{{theme.spacing.sm}}',
            padding: '{{theme.spacing.lg}}',
            borderWidth: '0px',
          },
          children: [
            {
              type: ComponentType.LABEL,
              name: 'Card Title',
              props: {
                text: 'Card Title',
                width: '100%',
                height: 'auto',
                fontSize: '{{theme.typography.fontSizeXl}}',
                fontWeight: '{{theme.typography.fontWeightSemibold}}',
                color: '{{theme.colors.text}}',
                fontFamily: '{{theme.typography.fontFamilyHeading}}',
                backgroundColor: 'transparent',
                textAlign: 'left',
                lineHeight: '{{theme.typography.lineHeightTight}}',
              },
            },
            {
              type: ComponentType.LABEL,
              name: 'Card Description',
              props: {
                text: 'This is a brief description of the card content. It provides context and invites the user to learn more.',
                width: '100%',
                height: 'auto',
                fontSize: '{{theme.typography.fontSizeMd}}',
                fontWeight: '{{theme.typography.fontWeightNormal}}',
                color: '{{theme.colors.onSurface}}',
                fontFamily: '{{theme.typography.fontFamily}}',
                backgroundColor: 'transparent',
                textAlign: 'left',
                lineHeight: '{{theme.typography.lineHeightRelaxed}}',
              },
            },
            {
              type: ComponentType.BUTTON,
              name: 'Card Action',
              props: {
                text: 'Read More',
                width: '100%',
                height: 'auto',
                backgroundColor: '{{theme.colors.primary}}',
                textColor: '{{theme.colors.onPrimary}}',
                variant: 'solid',
                size: 'md',
                actionType: 'none',
                borderStyle: 'none',
              },
            },
          ],
        },
      ],
    },
  ],
};
