import { ComponentType } from '@/types';
import { ComponentTemplate } from '../types';

export const ctaTemplate: ComponentTemplate = {
  id: 'cta-section',
  name: 'CTA Section',
  description: 'Centered call-to-action block with heading, description, and buttons',
  icon: 'Megaphone',
  components: [
    {
      type: ComponentType.CONTAINER,
      name: 'CTA Section',
      props: {
        width: '100%',
        height: 'auto',
        backgroundColor: '{{theme.colors.primary}}',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        gap: '{{theme.spacing.lg}}',
        padding: '{{theme.spacing.xxxxl}} {{theme.spacing.xl}}',
        borderWidth: '0px',
        borderRadius: '{{theme.radius.lg}}',
      },
      children: [
        {
          type: ComponentType.LABEL,
          name: 'CTA Heading',
          props: {
            text: 'Ready to Get Started?',
            width: '100%',
            height: 'auto',
            fontSize: '{{theme.typography.fontSizeXxl}}',
            fontWeight: '{{theme.typography.fontWeightBold}}',
            color: '{{theme.colors.onPrimary}}',
            fontFamily: '{{theme.typography.fontFamilyHeading}}',
            backgroundColor: 'transparent',
            textAlign: 'center',
            lineHeight: '{{theme.typography.lineHeightTight}}',
          },
        },
        {
          type: ComponentType.LABEL,
          name: 'CTA Description',
          props: {
            text: 'Join thousands of teams already using our platform to build better products, faster. Start your free trial today.',
            width: '100%',
            height: 'auto',
            fontSize: '{{theme.typography.fontSizeLg}}',
            fontWeight: '{{theme.typography.fontWeightNormal}}',
            color: '{{theme.colors.onPrimary}}',
            fontFamily: '{{theme.typography.fontFamily}}',
            backgroundColor: 'transparent',
            textAlign: 'center',
            lineHeight: '{{theme.typography.lineHeightRelaxed}}',
          },
        },
        {
          type: ComponentType.CONTAINER,
          name: 'CTA Buttons',
          props: {
            width: 'auto',
            height: 'auto',
            backgroundColor: 'transparent',
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            gap: '{{theme.spacing.md}}',
            padding: '{{theme.spacing.sm}} 0px',
            borderWidth: '0px',
          },
          children: [
            {
              type: ComponentType.BUTTON,
              name: 'CTA Primary',
              props: {
                text: 'Start Free Trial',
                width: 'auto',
                height: 'auto',
                backgroundColor: '{{theme.colors.onPrimary}}',
                textColor: '{{theme.colors.primary}}',
                variant: 'solid',
                size: 'lg',
                actionType: 'none',
                borderStyle: 'none',
              },
            },
            {
              type: ComponentType.BUTTON,
              name: 'CTA Secondary',
              props: {
                text: 'Contact Sales',
                width: 'auto',
                height: 'auto',
                backgroundColor: 'transparent',
                textColor: '{{theme.colors.onPrimary}}',
                variant: 'outlined',
                size: 'lg',
                actionType: 'none',
                borderStyle: 'solid',
                borderWidth: '2px',
                borderColor: '{{theme.colors.onPrimary}}',
              },
            },
          ],
        },
      ],
    },
  ],
};
