import { ComponentType } from '@/types';
import { ComponentTemplate } from '../types';

export const footerTemplate: ComponentTemplate = {
  id: 'footer',
  name: 'Footer (3-Column)',
  description: 'Dark footer with three columns of navigation links',
  icon: 'PanelBottom',
  components: [
    {
      type: ComponentType.CONTAINER,
      name: 'Footer',
      props: {
        width: '100%',
        height: 'auto',
        backgroundColor: '{{theme.colors.primary}}',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'stretch',
        padding: '{{theme.spacing.xxl}} {{theme.spacing.xl}}',
        gap: '{{theme.spacing.lg}}',
        borderWidth: '0px',
        semanticTag: 'footer',
      },
      children: [
        {
          type: ComponentType.CONTAINER,
          name: 'Footer Columns',
          props: {
            width: '100%',
            height: 'auto',
            backgroundColor: 'transparent',
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'flex-start',
            gap: '{{theme.spacing.xl}}',
            padding: '0px',
            borderWidth: '0px',
          },
          children: [
            {
              type: ComponentType.CONTAINER,
              name: 'Column 1 - Product',
              props: {
                width: '30%',
                height: 'auto',
                backgroundColor: 'transparent',
                flexDirection: 'column',
                justifyContent: 'flex-start',
                alignItems: 'flex-start',
                gap: '{{theme.spacing.sm}}',
                padding: '0px',
                borderWidth: '0px',
              },
              children: [
                {
                  type: ComponentType.LABEL,
                  name: 'Column 1 Heading',
                  props: {
                    text: 'Product',
                    width: '100%',
                    height: 'auto',
                    fontSize: '{{theme.typography.fontSizeMd}}',
                    fontWeight: '{{theme.typography.fontWeightSemibold}}',
                    color: '{{theme.colors.onPrimary}}',
                    fontFamily: '{{theme.typography.fontFamilyHeading}}',
                    backgroundColor: 'transparent',
                    textAlign: 'left',
                  },
                },
                {
                  type: ComponentType.LABEL,
                  name: 'Product Link 1',
                  props: {
                    text: 'Features',
                    width: '100%',
                    height: 'auto',
                    fontSize: '{{theme.typography.fontSizeSm}}',
                    fontWeight: '{{theme.typography.fontWeightNormal}}',
                    color: '{{theme.colors.onPrimary}}',
                    fontFamily: '{{theme.typography.fontFamily}}',
                    backgroundColor: 'transparent',
                    textAlign: 'left',
                    cursor: 'pointer',
                  },
                },
                {
                  type: ComponentType.LABEL,
                  name: 'Product Link 2',
                  props: {
                    text: 'Pricing',
                    width: '100%',
                    height: 'auto',
                    fontSize: '{{theme.typography.fontSizeSm}}',
                    fontWeight: '{{theme.typography.fontWeightNormal}}',
                    color: '{{theme.colors.onPrimary}}',
                    fontFamily: '{{theme.typography.fontFamily}}',
                    backgroundColor: 'transparent',
                    textAlign: 'left',
                    cursor: 'pointer',
                  },
                },
                {
                  type: ComponentType.LABEL,
                  name: 'Product Link 3',
                  props: {
                    text: 'Integrations',
                    width: '100%',
                    height: 'auto',
                    fontSize: '{{theme.typography.fontSizeSm}}',
                    fontWeight: '{{theme.typography.fontWeightNormal}}',
                    color: '{{theme.colors.onPrimary}}',
                    fontFamily: '{{theme.typography.fontFamily}}',
                    backgroundColor: 'transparent',
                    textAlign: 'left',
                    cursor: 'pointer',
                  },
                },
                {
                  type: ComponentType.LABEL,
                  name: 'Product Link 4',
                  props: {
                    text: 'Changelog',
                    width: '100%',
                    height: 'auto',
                    fontSize: '{{theme.typography.fontSizeSm}}',
                    fontWeight: '{{theme.typography.fontWeightNormal}}',
                    color: '{{theme.colors.onPrimary}}',
                    fontFamily: '{{theme.typography.fontFamily}}',
                    backgroundColor: 'transparent',
                    textAlign: 'left',
                    cursor: 'pointer',
                  },
                },
              ],
            },
            {
              type: ComponentType.CONTAINER,
              name: 'Column 2 - Company',
              props: {
                width: '30%',
                height: 'auto',
                backgroundColor: 'transparent',
                flexDirection: 'column',
                justifyContent: 'flex-start',
                alignItems: 'flex-start',
                gap: '{{theme.spacing.sm}}',
                padding: '0px',
                borderWidth: '0px',
              },
              children: [
                {
                  type: ComponentType.LABEL,
                  name: 'Column 2 Heading',
                  props: {
                    text: 'Company',
                    width: '100%',
                    height: 'auto',
                    fontSize: '{{theme.typography.fontSizeMd}}',
                    fontWeight: '{{theme.typography.fontWeightSemibold}}',
                    color: '{{theme.colors.onPrimary}}',
                    fontFamily: '{{theme.typography.fontFamilyHeading}}',
                    backgroundColor: 'transparent',
                    textAlign: 'left',
                  },
                },
                {
                  type: ComponentType.LABEL,
                  name: 'Company Link 1',
                  props: {
                    text: 'About Us',
                    width: '100%',
                    height: 'auto',
                    fontSize: '{{theme.typography.fontSizeSm}}',
                    fontWeight: '{{theme.typography.fontWeightNormal}}',
                    color: '{{theme.colors.onPrimary}}',
                    fontFamily: '{{theme.typography.fontFamily}}',
                    backgroundColor: 'transparent',
                    textAlign: 'left',
                    cursor: 'pointer',
                  },
                },
                {
                  type: ComponentType.LABEL,
                  name: 'Company Link 2',
                  props: {
                    text: 'Careers',
                    width: '100%',
                    height: 'auto',
                    fontSize: '{{theme.typography.fontSizeSm}}',
                    fontWeight: '{{theme.typography.fontWeightNormal}}',
                    color: '{{theme.colors.onPrimary}}',
                    fontFamily: '{{theme.typography.fontFamily}}',
                    backgroundColor: 'transparent',
                    textAlign: 'left',
                    cursor: 'pointer',
                  },
                },
                {
                  type: ComponentType.LABEL,
                  name: 'Company Link 3',
                  props: {
                    text: 'Blog',
                    width: '100%',
                    height: 'auto',
                    fontSize: '{{theme.typography.fontSizeSm}}',
                    fontWeight: '{{theme.typography.fontWeightNormal}}',
                    color: '{{theme.colors.onPrimary}}',
                    fontFamily: '{{theme.typography.fontFamily}}',
                    backgroundColor: 'transparent',
                    textAlign: 'left',
                    cursor: 'pointer',
                  },
                },
              ],
            },
            {
              type: ComponentType.CONTAINER,
              name: 'Column 3 - Support',
              props: {
                width: '30%',
                height: 'auto',
                backgroundColor: 'transparent',
                flexDirection: 'column',
                justifyContent: 'flex-start',
                alignItems: 'flex-start',
                gap: '{{theme.spacing.sm}}',
                padding: '0px',
                borderWidth: '0px',
              },
              children: [
                {
                  type: ComponentType.LABEL,
                  name: 'Column 3 Heading',
                  props: {
                    text: 'Support',
                    width: '100%',
                    height: 'auto',
                    fontSize: '{{theme.typography.fontSizeMd}}',
                    fontWeight: '{{theme.typography.fontWeightSemibold}}',
                    color: '{{theme.colors.onPrimary}}',
                    fontFamily: '{{theme.typography.fontFamilyHeading}}',
                    backgroundColor: 'transparent',
                    textAlign: 'left',
                  },
                },
                {
                  type: ComponentType.LABEL,
                  name: 'Support Link 1',
                  props: {
                    text: 'Help Center',
                    width: '100%',
                    height: 'auto',
                    fontSize: '{{theme.typography.fontSizeSm}}',
                    fontWeight: '{{theme.typography.fontWeightNormal}}',
                    color: '{{theme.colors.onPrimary}}',
                    fontFamily: '{{theme.typography.fontFamily}}',
                    backgroundColor: 'transparent',
                    textAlign: 'left',
                    cursor: 'pointer',
                  },
                },
                {
                  type: ComponentType.LABEL,
                  name: 'Support Link 2',
                  props: {
                    text: 'Documentation',
                    width: '100%',
                    height: 'auto',
                    fontSize: '{{theme.typography.fontSizeSm}}',
                    fontWeight: '{{theme.typography.fontWeightNormal}}',
                    color: '{{theme.colors.onPrimary}}',
                    fontFamily: '{{theme.typography.fontFamily}}',
                    backgroundColor: 'transparent',
                    textAlign: 'left',
                    cursor: 'pointer',
                  },
                },
                {
                  type: ComponentType.LABEL,
                  name: 'Support Link 3',
                  props: {
                    text: 'Contact Us',
                    width: '100%',
                    height: 'auto',
                    fontSize: '{{theme.typography.fontSizeSm}}',
                    fontWeight: '{{theme.typography.fontWeightNormal}}',
                    color: '{{theme.colors.onPrimary}}',
                    fontFamily: '{{theme.typography.fontFamily}}',
                    backgroundColor: 'transparent',
                    textAlign: 'left',
                    cursor: 'pointer',
                  },
                },
                {
                  type: ComponentType.LABEL,
                  name: 'Support Link 4',
                  props: {
                    text: 'Privacy Policy',
                    width: '100%',
                    height: 'auto',
                    fontSize: '{{theme.typography.fontSizeSm}}',
                    fontWeight: '{{theme.typography.fontWeightNormal}}',
                    color: '{{theme.colors.onPrimary}}',
                    fontFamily: '{{theme.typography.fontFamily}}',
                    backgroundColor: 'transparent',
                    textAlign: 'left',
                    cursor: 'pointer',
                  },
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
