import { ComponentType } from '@/types';
import { ComponentTemplate } from '../types';

export const heroTemplate: ComponentTemplate = {
  id: 'hero',
  name: 'Hero Section',
  description: 'Full-width hero with heading, subtitle, and call-to-action buttons',
  icon: 'Layers',
  components: [
    {
      type: ComponentType.CONTAINER,
      name: 'Hero Section',
      props: {
        width: '100%',
        height: 'auto',
        minHeight: '480px',
        backgroundColor: '{{theme.colors.primary}}',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        padding: '{{theme.spacing.xxxxl}} {{theme.spacing.xl}}',
        gap: '{{theme.spacing.lg}}',
        borderWidth: '0px',
      },
      children: [
        {
          type: ComponentType.LABEL,
          name: 'Hero Heading',
          props: {
            text: 'Build Something Amazing',
            width: '100%',
            height: 'auto',
            fontSize: '{{theme.typography.fontSizeXxxl}}',
            fontWeight: '{{theme.typography.fontWeightBold}}',
            color: '{{theme.colors.onPrimary}}',
            fontFamily: '{{theme.typography.fontFamilyHeading}}',
            backgroundColor: 'transparent',
            textAlign: 'center',
            lineHeight: '{{theme.typography.lineHeightTight}}',
            letterSpacing: '{{theme.typography.letterSpacingTight}}',
          },
        },
        {
          type: ComponentType.LABEL,
          name: 'Hero Subtitle',
          props: {
            text: 'Create beautiful, responsive applications in minutes with our powerful design tools and templates.',
            width: '100%',
            height: 'auto',
            fontSize: '{{theme.typography.fontSizeLg}}',
            fontWeight: '{{theme.typography.fontWeightNormal}}',
            color: '{{theme.colors.onPrimary}}',
            fontFamily: '{{theme.typography.fontFamily}}',
            backgroundColor: 'transparent',
            textAlign: 'center',
            lineHeight: '{{theme.typography.lineHeightRelaxed}}',
          },
        },
        {
          type: ComponentType.CONTAINER,
          name: 'Hero Buttons',
          props: {
            width: 'auto',
            height: 'auto',
            backgroundColor: 'transparent',
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            gap: '{{theme.spacing.md}}',
            padding: '{{theme.spacing.sm}} 0px',
            borderWidth: '0px',
          },
          children: [
            {
              type: ComponentType.BUTTON,
              name: 'Primary CTA',
              props: {
                text: 'Get Started Free',
                width: 'auto',
                height: 'auto',
                backgroundColor: '{{theme.colors.onPrimary}}',
                textColor: '{{theme.colors.primary}}',
                variant: 'solid',
                size: 'lg',
                actionType: 'none',
                borderStyle: 'none',
              },
            },
            {
              type: ComponentType.BUTTON,
              name: 'Secondary CTA',
              props: {
                text: 'Learn More',
                width: 'auto',
                height: 'auto',
                backgroundColor: 'transparent',
                textColor: '{{theme.colors.onPrimary}}',
                variant: 'outlined',
                size: 'lg',
                actionType: 'none',
                borderStyle: 'solid',
                borderWidth: '2px',
                borderColor: '{{theme.colors.onPrimary}}',
              },
            },
          ],
        },
      ],
    },
  ],
};
