import { ComponentType } from '@/types';
import { ComponentTemplate } from '../types';

export const navbarTemplate: ComponentTemplate = {
  id: 'navbar',
  name: 'Navigation Bar',
  description: 'Horizontal nav bar with logo, links, and CTA button',
  icon: 'Menu',
  components: [
    {
      type: ComponentType.CONTAINER,
      name: 'Navbar',
      props: {
        width: '100%',
        height: 'auto',
        backgroundColor: '{{theme.colors.surface}}',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '{{theme.spacing.md}} {{theme.spacing.lg}}',
        gap: '{{theme.spacing.md}}',
        borderWidth: '0px',
        borderBottomWidth: '1px',
        borderStyle: 'solid',
        borderColor: '{{theme.colors.border}}',
        semanticTag: 'nav',
      },
      children: [
        {
          type: ComponentType.LABEL,
          name: 'Logo',
          props: {
            text: 'Brand',
            width: 'auto',
            height: 'auto',
            fontSize: '{{theme.typography.fontSizeXl}}',
            fontWeight: '{{theme.typography.fontWeightBold}}',
            color: '{{theme.colors.primary}}',
            fontFamily: '{{theme.typography.fontFamilyHeading}}',
            backgroundColor: 'transparent',
            textAlign: 'left',
            cursor: 'pointer',
          },
        },
        {
          type: ComponentType.CONTAINER,
          name: 'Nav Links',
          props: {
            width: 'auto',
            height: 'auto',
            backgroundColor: 'transparent',
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            gap: '{{theme.spacing.lg}}',
            padding: '0px',
            borderWidth: '0px',
            flexGrow: 1,
          },
          children: [
            {
              type: ComponentType.LABEL,
              name: 'Nav Link 1',
              props: {
                text: 'Home',
                width: 'auto',
                height: 'auto',
                fontSize: '{{theme.typography.fontSizeMd}}',
                fontWeight: '{{theme.typography.fontWeightMedium}}',
                color: '{{theme.colors.text}}',
                fontFamily: '{{theme.typography.fontFamily}}',
                backgroundColor: 'transparent',
                textAlign: 'center',
                cursor: 'pointer',
              },
            },
            {
              type: ComponentType.LABEL,
              name: 'Nav Link 2',
              props: {
                text: 'Features',
                width: 'auto',
                height: 'auto',
                fontSize: '{{theme.typography.fontSizeMd}}',
                fontWeight: '{{theme.typography.fontWeightMedium}}',
                color: '{{theme.colors.text}}',
                fontFamily: '{{theme.typography.fontFamily}}',
                backgroundColor: 'transparent',
                textAlign: 'center',
                cursor: 'pointer',
              },
            },
            {
              type: ComponentType.LABEL,
              name: 'Nav Link 3',
              props: {
                text: 'Pricing',
                width: 'auto',
                height: 'auto',
                fontSize: '{{theme.typography.fontSizeMd}}',
                fontWeight: '{{theme.typography.fontWeightMedium}}',
                color: '{{theme.colors.text}}',
                fontFamily: '{{theme.typography.fontFamily}}',
                backgroundColor: 'transparent',
                textAlign: 'center',
                cursor: 'pointer',
              },
            },
            {
              type: ComponentType.LABEL,
              name: 'Nav Link 4',
              props: {
                text: 'About',
                width: 'auto',
                height: 'auto',
                fontSize: '{{theme.typography.fontSizeMd}}',
                fontWeight: '{{theme.typography.fontWeightMedium}}',
                color: '{{theme.colors.text}}',
                fontFamily: '{{theme.typography.fontFamily}}',
                backgroundColor: 'transparent',
                textAlign: 'center',
                cursor: 'pointer',
              },
            },
          ],
        },
        {
          type: ComponentType.BUTTON,
          name: 'CTA Button',
          props: {
            text: 'Get Started',
            width: 'auto',
            height: 'auto',
            backgroundColor: '{{theme.colors.primary}}',
            textColor: '{{theme.colors.onPrimary}}',
            variant: 'solid',
            size: 'md',
            actionType: 'none',
            borderStyle: 'none',
          },
        },
      ],
    },
  ],
};
