import { Theme, GlobalTheme } from '@/types';

// ============================================================================
// Professional Blue — Corporate, trustworthy
// ============================================================================
const professionalBlueLight: Theme = {
  colors: {
    primary: '#2563EB',
    onPrimary: '#FFFFFF',
    secondary: '#0891B2',
    onSecondary: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F8FAFC',
    text: '#0F172A',
    border: '#CBD5E1',
    primaryLight: '#60A5FA',
    primaryDark: '#1D4ED8',
    secondaryLight: '#22D3EE',
    secondaryDark: '#0E7490',
    error: '#DC2626',
    onError: '#FFFFFF',
    warning: '#D97706',
    onWarning: '#FFFFFF',
    success: '#16A34A',
    onSuccess: '#FFFFFF',
    info: '#2563EB',
    onInfo: '#FFFFFF',
    surfaceVariant: '#F1F5F9',
    onSurface: '#1E293B',
    onBackground: '#1E293B',
    hover: '#EFF6FF',
    focus: '#3B82F6',
    disabled: '#E2E8F0',
    onDisabled: '#94A3B8',
    outline: '#94A3B8',
    shadow: '#0F172A',
    overlay: 'rgba(15, 23, 42, 0.5)',
    link: '#2563EB',
  },
  font: { family: 'Inter, system-ui, sans-serif' },
  border: {
    width: '1px',
    style: 'solid',
    widthThin: '1px',
    widthMedium: '2px',
    widthThick: '3px',
  },
  radius: {
    default: '6px',
    none: '0px',
    sm: '4px',
    md: '6px',
    lg: '8px',
    xl: '12px',
    full: '9999px',
  },
  spacing: {
    xs: '2px',
    sm: '4px',
    md: '8px',
    lg: '16px',
    xl: '24px',
    xxl: '32px',
    xxxl: '48px',
    xxxxl: '64px',
  },
  typography: {
    fontFamily: 'Inter, system-ui, sans-serif',
    fontFamilyHeading: 'Inter, system-ui, sans-serif',
    fontFamilyMono: 'JetBrains Mono, Menlo, monospace',
    fontSizeXs: '10px',
    fontSizeSm: '12px',
    fontSizeMd: '14px',
    fontSizeLg: '16px',
    fontSizeXl: '20px',
    fontSizeXxl: '24px',
    fontSizeXxxl: '30px',
    fontWeightLight: '300',
    fontWeightNormal: '400',
    fontWeightMedium: '500',
    fontWeightSemibold: '600',
    fontWeightBold: '700',
    lineHeightTight: '1.25',
    lineHeightNormal: '1.5',
    lineHeightRelaxed: '1.75',
    letterSpacingTight: '-0.025em',
    letterSpacingNormal: '0em',
    letterSpacingWide: '0.025em',
  },
  shadow: {
    none: 'none',
    sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
    lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)',
    xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
    inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.05)',
  },
  transition: {
    durationFast: '150ms',
    durationNormal: '250ms',
    durationSlow: '400ms',
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
  },
};

const professionalBlueDark: Theme = {
  ...professionalBlueLight,
  colors: {
    primary: '#60A5FA',
    onPrimary: '#1E3A5F',
    secondary: '#22D3EE',
    onSecondary: '#164E63',
    background: '#0F172A',
    surface: '#1E293B',
    text: '#F1F5F9',
    border: '#334155',
    primaryLight: '#93C5FD',
    primaryDark: '#2563EB',
    secondaryLight: '#67E8F9',
    secondaryDark: '#0891B2',
    error: '#F87171',
    onError: '#7F1D1D',
    warning: '#FBBF24',
    onWarning: '#78350F',
    success: '#4ADE80',
    onSuccess: '#14532D',
    info: '#60A5FA',
    onInfo: '#1E3A5F',
    surfaceVariant: '#334155',
    onSurface: '#E2E8F0',
    onBackground: '#E2E8F0',
    hover: '#1E3A5F',
    focus: '#60A5FA',
    disabled: '#334155',
    onDisabled: '#64748B',
    outline: '#475569',
    shadow: '#000000',
    overlay: 'rgba(0, 0, 0, 0.6)',
    link: '#60A5FA',
  },
  shadow: {
    none: 'none',
    sm: '0 1px 2px 0 rgba(0, 0, 0, 0.3)',
    md: '0 4px 6px -1px rgba(0, 0, 0, 0.4), 0 2px 4px -2px rgba(0, 0, 0, 0.3)',
    lg: '0 10px 15px -3px rgba(0, 0, 0, 0.4), 0 4px 6px -4px rgba(0, 0, 0, 0.3)',
    xl: '0 20px 25px -5px rgba(0, 0, 0, 0.5), 0 8px 10px -6px rgba(0, 0, 0, 0.4)',
    inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.3)',
  },
};

// ============================================================================
// Warm Earth — Organic, approachable
// ============================================================================
const warmEarthLight: Theme = {
  ...professionalBlueLight,
  colors: {
    primary: '#B45309',
    onPrimary: '#FFFFFF',
    secondary: '#059669',
    onSecondary: '#FFFFFF',
    background: '#FFFBF5',
    surface: '#FEF7ED',
    text: '#1C1917',
    border: '#D6D3D1',
    primaryLight: '#F59E0B',
    primaryDark: '#92400E',
    secondaryLight: '#34D399',
    secondaryDark: '#047857',
    error: '#DC2626',
    onError: '#FFFFFF',
    warning: '#D97706',
    onWarning: '#FFFFFF',
    success: '#16A34A',
    onSuccess: '#FFFFFF',
    info: '#0284C7',
    onInfo: '#FFFFFF',
    surfaceVariant: '#F5F0EB',
    onSurface: '#292524',
    onBackground: '#292524',
    hover: '#FEF3C7',
    focus: '#B45309',
    disabled: '#E7E5E4',
    onDisabled: '#A8A29E',
    outline: '#A8A29E',
    shadow: '#1C1917',
    overlay: 'rgba(28, 25, 23, 0.5)',
    link: '#B45309',
  },
  font: { family: 'DM Sans, system-ui, sans-serif' },
  typography: {
    ...professionalBlueLight.typography,
    fontFamily: 'DM Sans, system-ui, sans-serif',
    fontFamilyHeading: 'DM Sans, system-ui, sans-serif',
  },
};

const warmEarthDark: Theme = {
  ...warmEarthLight,
  colors: {
    primary: '#F59E0B',
    onPrimary: '#451A03',
    secondary: '#34D399',
    onSecondary: '#064E3B',
    background: '#1C1917',
    surface: '#292524',
    text: '#F5F5F4',
    border: '#44403C',
    primaryLight: '#FCD34D',
    primaryDark: '#B45309',
    secondaryLight: '#6EE7B7',
    secondaryDark: '#059669',
    error: '#F87171',
    onError: '#7F1D1D',
    warning: '#FBBF24',
    onWarning: '#78350F',
    success: '#4ADE80',
    onSuccess: '#14532D',
    info: '#38BDF8',
    onInfo: '#0C4A6E',
    surfaceVariant: '#44403C',
    onSurface: '#E7E5E4',
    onBackground: '#E7E5E4',
    hover: '#451A03',
    focus: '#F59E0B',
    disabled: '#44403C',
    onDisabled: '#78716C',
    outline: '#57534E',
    shadow: '#000000',
    overlay: 'rgba(0, 0, 0, 0.6)',
    link: '#F59E0B',
  },
  shadow: {
    ...professionalBlueDark.shadow,
  },
};

// ============================================================================
// Minimal Monochrome — Clean, stark
// ============================================================================
const minimalMonoLight: Theme = {
  ...professionalBlueLight,
  colors: {
    primary: '#18181B',
    onPrimary: '#FFFFFF',
    secondary: '#52525B',
    onSecondary: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#FAFAFA',
    text: '#09090B',
    border: '#E4E4E7',
    primaryLight: '#3F3F46',
    primaryDark: '#09090B',
    secondaryLight: '#71717A',
    secondaryDark: '#3F3F46',
    error: '#EF4444',
    onError: '#FFFFFF',
    warning: '#EAB308',
    onWarning: '#422006',
    success: '#22C55E',
    onSuccess: '#FFFFFF',
    info: '#3B82F6',
    onInfo: '#FFFFFF',
    surfaceVariant: '#F4F4F5',
    onSurface: '#18181B',
    onBackground: '#18181B',
    hover: '#F4F4F5',
    focus: '#18181B',
    disabled: '#E4E4E7',
    onDisabled: '#A1A1AA',
    outline: '#A1A1AA',
    shadow: '#09090B',
    overlay: 'rgba(9, 9, 11, 0.5)',
    link: '#18181B',
  },
  font: { family: 'Geist, system-ui, sans-serif' },
  typography: {
    ...professionalBlueLight.typography,
    fontFamily: 'Geist, system-ui, sans-serif',
    fontFamilyHeading: 'Geist, system-ui, sans-serif',
  },
};

const minimalMonoDark: Theme = {
  ...minimalMonoLight,
  colors: {
    primary: '#FAFAFA',
    onPrimary: '#18181B',
    secondary: '#A1A1AA',
    onSecondary: '#18181B',
    background: '#09090B',
    surface: '#18181B',
    text: '#FAFAFA',
    border: '#27272A',
    primaryLight: '#FFFFFF',
    primaryDark: '#D4D4D8',
    secondaryLight: '#D4D4D8',
    secondaryDark: '#71717A',
    error: '#F87171',
    onError: '#7F1D1D',
    warning: '#FACC15',
    onWarning: '#422006',
    success: '#4ADE80',
    onSuccess: '#14532D',
    info: '#60A5FA',
    onInfo: '#1E3A5F',
    surfaceVariant: '#27272A',
    onSurface: '#E4E4E7',
    onBackground: '#E4E4E7',
    hover: '#27272A',
    focus: '#FAFAFA',
    disabled: '#27272A',
    onDisabled: '#52525B',
    outline: '#3F3F46',
    shadow: '#000000',
    overlay: 'rgba(0, 0, 0, 0.7)',
    link: '#FAFAFA',
  },
  shadow: {
    ...professionalBlueDark.shadow,
  },
};

// ============================================================================
// Vibrant Startup — Bold, energetic
// ============================================================================
const vibrantStartupLight: Theme = {
  ...professionalBlueLight,
  colors: {
    primary: '#7C3AED',
    onPrimary: '#FFFFFF',
    secondary: '#EC4899',
    onSecondary: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#FAF5FF',
    text: '#1E1B4B',
    border: '#DDD6FE',
    primaryLight: '#A78BFA',
    primaryDark: '#6D28D9',
    secondaryLight: '#F472B6',
    secondaryDark: '#DB2777',
    error: '#EF4444',
    onError: '#FFFFFF',
    warning: '#F59E0B',
    onWarning: '#FFFFFF',
    success: '#10B981',
    onSuccess: '#FFFFFF',
    info: '#6366F1',
    onInfo: '#FFFFFF',
    surfaceVariant: '#EDE9FE',
    onSurface: '#312E81',
    onBackground: '#312E81',
    hover: '#EDE9FE',
    focus: '#7C3AED',
    disabled: '#E9D5FF',
    onDisabled: '#A78BFA',
    outline: '#A78BFA',
    shadow: '#1E1B4B',
    overlay: 'rgba(30, 27, 75, 0.5)',
    link: '#7C3AED',
  },
  font: { family: 'Plus Jakarta Sans, system-ui, sans-serif' },
  typography: {
    ...professionalBlueLight.typography,
    fontFamily: 'Plus Jakarta Sans, system-ui, sans-serif',
    fontFamilyHeading: 'Plus Jakarta Sans, system-ui, sans-serif',
  },
};

const vibrantStartupDark: Theme = {
  ...vibrantStartupLight,
  colors: {
    primary: '#A78BFA',
    onPrimary: '#2E1065',
    secondary: '#F472B6',
    onSecondary: '#831843',
    background: '#0F0D1A',
    surface: '#1E1B2E',
    text: '#F5F3FF',
    border: '#3B3566',
    primaryLight: '#C4B5FD',
    primaryDark: '#7C3AED',
    secondaryLight: '#F9A8D4',
    secondaryDark: '#EC4899',
    error: '#F87171',
    onError: '#7F1D1D',
    warning: '#FBBF24',
    onWarning: '#78350F',
    success: '#34D399',
    onSuccess: '#064E3B',
    info: '#818CF8',
    onInfo: '#312E81',
    surfaceVariant: '#3B3566',
    onSurface: '#E9E5FF',
    onBackground: '#E9E5FF',
    hover: '#2E1065',
    focus: '#A78BFA',
    disabled: '#3B3566',
    onDisabled: '#6D5DB5',
    outline: '#5B52A0',
    shadow: '#000000',
    overlay: 'rgba(0, 0, 0, 0.6)',
    link: '#A78BFA',
  },
  shadow: {
    ...professionalBlueDark.shadow,
  },
};

// ============================================================================
// Exports
// ============================================================================

export const presetThemes: GlobalTheme[] = [
  {
    id: 'preset_professional_blue_light',
    name: 'Professional Blue',
    type: 'light',
    theme: professionalBlueLight,
    description: 'Corporate, trustworthy — Slate/Blue palette with Inter font',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'preset_professional_blue_dark',
    name: 'Professional Blue Dark',
    type: 'dark',
    theme: professionalBlueDark,
    description: 'Corporate, trustworthy — Dark slate with bright blue accents',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'preset_warm_earth_light',
    name: 'Warm Earth',
    type: 'light',
    theme: warmEarthLight,
    description: 'Organic, approachable — Stone/Amber/Emerald with DM Sans',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'preset_warm_earth_dark',
    name: 'Warm Earth Dark',
    type: 'dark',
    theme: warmEarthDark,
    description: 'Organic, approachable — Dark stone with warm amber',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'preset_minimal_mono_light',
    name: 'Minimal Monochrome',
    type: 'light',
    theme: minimalMonoLight,
    description: 'Clean, stark — Pure gray/neutral scale with Geist',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'preset_minimal_mono_dark',
    name: 'Minimal Monochrome Dark',
    type: 'dark',
    theme: minimalMonoDark,
    description: 'Clean, stark — Dark neutral scale',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'preset_vibrant_startup_light',
    name: 'Vibrant Startup',
    type: 'light',
    theme: vibrantStartupLight,
    description: 'Bold, energetic — Violet/Rose/Indigo with Plus Jakarta Sans',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'preset_vibrant_startup_dark',
    name: 'Vibrant Startup Dark',
    type: 'dark',
    theme: vibrantStartupDark,
    description: 'Bold, energetic — Dark violet with bright pink accents',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
];

export function getDefaultTheme(type: 'light' | 'dark'): Theme {
  return type === 'dark' ? professionalBlueDark : professionalBlueLight;
}

export const defaultLightTheme: Theme = professionalBlueLight;
export const defaultDarkTheme: Theme = professionalBlueDark;
